[project]
name = ""
version = ""
description = ""
authors = [
    {name = "", email = ""},
]
dependencies = [
    "flask>=3.0.0",
    "flask-login>=0.6.3",
    "flask-wtf>=1.2.1",
]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

